/* eslint-disable max-len */
const foods = [{
  id: 'ayam_bakar',
  name: 'Ayam Bakar',
  description: 'Ayam bakar is an Indonesian and Malaysian dish, consisting of charcoal-grilled chicken. Ayam bakar literally means "roasted chicken" in Indonesian and Malay. In Java, the chicken is usually marinated with the mixture of kecap manis (sweet soy sauce) and coconut oil, applied with a brush during grilling. The bumbu spice mixture may vary among regions, but usually it consists of combination of ground shallot, garlic, chilli pepper, coriander, tamarind juice, candlenut, turmeric, galangal and salt. In Java, ayam bakar usually tastes rather sweet because of the generous amount of sweet soy sauce either as marination or dipping sauce, while the ayam bakar Padang, Bali, Lombok and most of Sumatra are usually spicier and more reddish in colour due to the generous amount of chilli pepper, turmeric and other spices, and the absence of sweet soy sauce. The chicken pieces are usually partially cooked in the spice mixture using a small fire prior to grilling, in order for the chicken to absorb the spices. During grilling process the remaining spices are applied upon the chicken. Ayam bakar is usually served with sambal terasi (chilli with terasi) or sambal kecap (sliced chilli and shallot in sweet soy sauce) as dipping sauce or condiment and slices of cucumber and tomato as garnishing.',
  ingredients: '800 g (1 head) chicken, cut into 4 parts,\n4 bay leaves,\n2 lemongrass stalks, bruised,\n20 g tamarind, dissolved in 3 tablespoons hot water,\n500 ml coconut milk,\n2 tbsp oil, for frying,\n10 red onions,\n5 cloves of garlic,\n1 tbsp coriander (roasted),\n5 pecans,\nhalf tsp pepper powder,\n3 cm turmeric,\n50 g brown sugar,\n1 tsp salt,\n1 tsp sugar,\n1 tbsp Bango Sweet Soy Sauce',
  // Paragraph method
  howtocook: "First, Heat oil, saute ground spices, bay leaf, and lemongrass until fragrant.\nSecond, Add the tamarind water and chicken, mix well.\nThird, Pour in the coconut milk, stir gently so that the coconut milk doesn't break.\nFourth, Cook until the coconut milk is absorbed and the chicken is tender. Remove and set aside.\nFifth, Heat the pan, grill the chicken while smeared with ground spices and soy sauce. Bake until brown.\nLast, Lift and serve.",
  // Step by step method
  first: 'First, Heat oil, saute ground spices, bay leaf, and lemongrass until fragrant.',
  second: 'Second, Add the tamarind water and chicken, mix well.',
  third: "Third, Pour in the coconut milk, stir gently so that the coconut milk doesn't break.",
  fourth: 'Fourth, Cook until the coconut milk is absorbed and the chicken is tender. Remove and set aside.',
  fifth: 'Fifth, Heat the pan, grill the chicken while smeared with ground spices and soy sauce. Bake until brown.',
  sixth: 'Last, Lift and serve.',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'bandeng_presto',
  name: 'Bandeng Presto ',
  description: 'Bandeng presto is a typical Indonesian food originating from Juwana District, Pati Regency, Central Java and Gresik, East Java. This dish is made from milkfish (Chanos chanos) seasoned with garlic, turmeric and salt.This milkfish is then cooked on a banana leaf base in a pressure cooker. Presto is a method of cooking with high pressure steam. Food cooked this way is placed in a pan that can be locked tightly. The water in this pot is then heated until it boils. The water vapor that arises will cook the food in this pan. Because milkfish are known to have many spines, pressure cookers are a favorite food because with this method of cooking, these spines become very soft.',
  ingredients: '5 whitefish (weighing 200 grams each), clean and wash,\n5 bay leaves,\n1 tbsp red onion, puree,\n1 tsp garlic, puree,\n1 tbsp salt, grind,\n1 tsp turmeric sliced, puree,\n300 ml water',
  howtocook: 'First, Take a basin, put the milkfish in it. Coat with ground spices except bay leaf. Leave it for an hour.\nSecond, Prepare a pressure cooker, line the bottom with bay leaves. Arrange the seasoned milkfish, pour water. Close presto tightly, lock.\nThird, Cook the milkfish for 60 minutes. Lift.\nFourth, Open the temperature control valve, let the steam out until it runs out. Pick up the fish.\nLast, Serve the milkfish presto while warm with rice or fried first.',
  // Step by step method
  first: 'First, Take a basin, put the milkfish in it. Coat with ground spices except bay leaf. Leave it for an hour.',
  second: 'Second, Prepare a pressure cooker, line the bottom with bay leaves. Arrange the seasoned milkfish, pour water. Close presto tightly, lock.',
  third: 'Third, Cook the milkfish for 60 minutes. Lift.',
  fourth: 'Fourth, Open the temperature control valve, let the steam out until it runs out. Pick up the fish.',
  fifth: 'Serve the milkfish presto while warm with rice or fried first.',
  sixth: '',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'gudeg',
  name: 'Gudeg',
  description: 'Gudeg is a traditional Javanese dish from Yogyakarta and Central Java, Indonesia. Gudeg is made from young unripe jack fruit (Javanese: gori, Indonesian: nangka muda) stewed for several hours with palm sugar, and coconut milk. Additional spices include garlic, shallot, candlenut, coriander seed, galangal, bay leaves, and teak leaves, the latter giving a reddish-brown color to the dish. It is often described as "green jack fruit sweet stew".',
  ingredients: '1 Tbsp cooking oil,\n4 bay leaves (daun salam),\n4 pieces of bone-in chicken thighs/drumstick,\n1 ½ lb canned green jack fruit,\n½ cup red beans (soaked for 4 hours) optional,\n6 cups coconut milk,\n1 black tea tea bag,\n50 gr Palm sugar or dark brown sugar,\nPinch of salt,\n4 hard-boiled eggs,\n4 garlic cloves peeled and finely chopped,\n1 tsp coriander seeds,\n8 candlenuts closest substitution is macademia nuts, or 10 blanched almonds, chopped,\n3 shallots,\n1 inch ginger,\n2 inch galangal',
  howtocook: 'First, Place all the ingredients for ground spices in a food processor and process into a paste. Add a little bit of water if needed to get it going.\nSecond, Preheat a large pot or dutch oven with cooking oil. Add the ground spices and bay leaves and saute until fragrant, about 5 minutes.\nThird, Add the chicken, jackfruit, red beans and stir to mix. Pour in the coconut milk, tea bag, salt, and brown sugar.\nFourth, Bring it to a boil and then lower the heat and cover to let it cook for the next 1 hour. Give it a stir every now and then.\nFifth, Uncover and then add in the hard-boiled eggs and let it cook again for another hour or so until the jackfruit is soft to the point where you can easily shred it with a fork. The beans should be soft and chicken meat is almost falling off the bones. The liquid should be almost all absorbed at this point and the eggs are nicely tinted with brown color.\nLast, Serve with rice and sambal on the side.',
  first: 'First, Place all the ingredients for ground spices in a food processor and process into a paste. Add a little bit of water if needed to get it going.',
  second: 'Second, Preheat a large pot or dutch oven with cooking oil. Add the ground spices and bay leaves and saute until fragrant, about 5 minutes.',
  third: 'Third, Add the chicken, jackfruit, red beans and stir to mix. Pour in the coconut milk, tea bag, salt, and brown sugar.',
  fourth: 'Fourth, Bring it to a boil and then lower the heat and cover to let it cook for the next 1 hour. Give it a stir every now and then.',
  fifth: 'Fifth, Uncover and then add in the hard-boiled eggs and let it cook again for another hour or so until the jackfruit is soft to the point where you can easily shred it with a fork. The beans should be soft and chicken meat is almost falling off the bones. The liquid should be almost all absorbed at this point and the eggs are nicely tinted with brown color.',
  sixth: 'Last, Serve with rice and sambal on the side.',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'nasi_pindang',
  name: 'Nasi Pindang',
  description: 'Nasi Pindang is a dish of rice and meat served with pindang sauce and melinjo or so leaves. It is a typical food from the people of Kudus Regency, precisely in Colo Village. Nasi Pindang usually served in every Kudus community that has a celebration / party. However, over time, Nasi Pindang has been sold everywhere from restaurants to street stalls. Nasi Pindang originally came from Kudus. Nasi Pindang in Kudus originally used buffalo meat because in Kudus there is a prohibition on eating beef. But now usually Nasi Pindang is served with beef or chicken.',
  ingredients: '500g beef brisket,\n2L water,\n2 bay leaves,\n3 lemongrass stalks, bruised,\n7 lime leaves,\n2 tbsp Bango Sweet Soy Sauce,\nsalt,\n5g tamarind,\n100g melinjo leaves,\n4 tbsp cooking oil,\n35 skinned red onions (roasted & peeled),\n15 g garlic,\n4 cm turmeric,\n1 tsp roasted coriander,\n½ tsp shrimp paste,\n4 pieces of old palm',
  howtocook: 'First, In a frying pan, heat the oil, then add the lemon grass, bay leaf and lime leaves, stir briefly, then add the ground spices, stir-fry until fragrant.\nSecond, Add the pieces of meat, then stir until the spices are evenly distributed. Add boiled water, bring to a boil, then reduce heat and cover the pot. Cook until the meat is tender.\nThird, Add salt, brown sugar, tamarind water and Bango Sweet Soy Sauce, stir until the spices are absorbed. Add the melinjo leaves and cook until the melinjo leaves are cooked, remove from heat.\nFourth, Serve.',
  first: 'First, In a frying pan, heat the oil, then add the lemon grass, bay leaf and lime leaves, stir briefly, then add the ground spices, stir-fry until fragrant.',
  second: 'Second, Add the pieces of meat, then stir until the spices are evenly distributed. Add boiled water, bring to a boil, then reduce heat and cover the pot. Cook until the meat is tender.',
  third: 'Third, Add salt, brown sugar, tamarind water and Bango Sweet Soy Sauce, stir until the spices are absorbed.',
  fourth: 'Fourth, Add the melinjo leaves and cook until the melinjo leaves are cooked, remove from heat.',
  fifth: 'Last, Serve.',
  sixth: '',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'sate',
  name: 'Sate',
  description: 'Satay or sate in Indonesian and Malay spelling, is a Southeast Asian dish of seasoned, skewered and grilled meat, served with a sauce. The earliest preparations of satay is believed to have originated in Javanese cuisine, but has spread to almost anywhere in Indonesia, where it has become a national dish. Indonesian satay is often served with peanut sauce a sauce made from peanut butter, and is often accompanied with lontong, a type of rice cake, though the diversity of the country has produced a wide variety of satay recipes. Satay may consist of diced or sliced chicken, goat, mutton, beef, pork, fish, other meats, or tofu; bamboo skewers are often used, while rustic style of preparations employ skewers from the midrib of the coconut palm frond. These are grilled or barbecued over a wood or charcoal fire, then served with various spicy seasonings. Satay can be served in various sauces; however, most often they are served in a combination of soy and peanut sauce. Hence, peanut sauce is often called satay sauce. It is popular as street food, and it can be obtained from a travelling satay vendor, from a street-side tent-restaurant, in an upper-class restaurant, or at traditional celebration feasts.',
  ingredients: '1/4 cup coconut milk,\n2 tablespoons reduced sodium soy sauce,\n2 1/2 teaspoons yellow curry powder,\n1 1/2 teaspoons turmeric,\n3 cloves garlic, minced,\n1 tablespoon freshly grated ginger,\n1 tablespoon brown sugar,\n1 tablespoon fish sauce,\n2 pounds boneless, skinless chicken thighs, cut into 1-inch chunks,\n1 tablespoon canola oil,\nKosher salt and freshly ground black pepper, to taste,\nFOR THE PEANUT SAUCE:\n3 tablespoons creamy peanut butter,\n1 tablespoon reduced sodium soy sauce,\n1 tablespoon freshly squeezed lime juice,\n2 teaspoons brown sugar,\n2 teaspoons chili garlic sauce, or more, to taste,\n1 teaspoon freshly grated ginger.',
  howtocook: 'First, To make the peanut sauce, whisk together peanut butter, soy sauce, lime juice, brown sugar, chili garlic sauce and ginger in a small bowl. Whisk in 2-3 tablespoons water until desired consistency is reached; set aside.\nSecond, In a medium bowl, combine coconut milk, soy sauce, curry powder, turmeric, garlic, ginger, brown sugar and fish sauce.\nThird, In a gallon size Ziploc bag or large bowl, combine chicken and coconut milk mixture; marinate for at least 2 hours to overnight, turning the bag occasionally.\nFourth, Drain the chicken from the marinade, discarding the marinade.\nFifth, Preheat grill to medium high heat. Thread chicken onto skewers. Brush with canola oil; season with salt and pepper, to taste.\nSixth, Add skewers to grill, and cook, turning occasionally, until the chicken is completely cooked through, reaching an internal temperature of 165 degrees F, about 12-15 minutes.\nLast, Serve immediately with peanut sauce.',
  first: 'First, To make the peanut sauce, whisk together peanut butter, soy sauce, lime juice, brown sugar, chili garlic sauce and ginger in a small bowl. Whisk in 2-3 tablespoons water until desired consistency is reached; set aside.',
  second: 'Second, In a medium bowl, combine coconut milk, soy sauce, curry powder, turmeric, garlic, ginger, brown sugar and fish sauce.',
  third: 'Third, In a gallon size Ziploc bag or large bowl, combine chicken and coconut milk mixture; marinate for at least 2 hours to overnight, turning the bag occasionally.',
  fourth: 'Fourth, Drain the chicken from the marinade, discarding the marinade.',
  fifth: 'Fifth, Preheat grill to medium high heat. Thread chicken onto skewers. Brush with canola oil; season with salt and pepper, to taste.',
  sixth: 'Sixth, Add skewers to grill, and cook, turning occasionally, until the chicken is completely cooked through, reaching an internal temperature of 165 degrees F, about 12-15 minutes.',
  seventh: 'Last, Serve immediately with peanut sauce.',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'bakso',
  name: 'Bakso',
  description: 'Bakso is Indonesian meatball. When served with noodles and broth, the dish is mee bakso. But meatballs are ubiquitous in Asian noodle soups—what makes the Indonesian bakso different? Bakso, whether meat, seafood or chicken-based, are denser and richer because of the paste used to make them. The paste is called surimi. Like laksa, there is no definitive recipe for making mee bakso. The soup can be made from meat, seafood or chicken, or a combination of all of them. The meatballs can have beef, pork, chicken, fish or other seafood.',
  ingredients: '5 pounds beef bones,\n1 (1-inch) piece ginger peeled,\n4 cloves garlic lightly crushed,\n1 (2-inch) cinnamon stick,\n3 pods cardamom lightly pounded,\n3 whole cloves,\n6 whole peppercorns,\n18 medium meatballs,\n1 small carrot thinly sliced,\n4 cups spinach or bok choy,\n3 cups cooked egg noodles,\n½ cup store-bought or homemade crisp-fried shallots,\n3 large hard boiled eggs optional',
  howtocook: 'Step 1 Place the beef bones in a pot. Cover with water;\nStep 2 Bring to the boil; skim off any scum that rises;\nStep 3 Add the ginger, garlic, cinnamon, cardamom, cloves, and peppercorns. Simmer for at least two hours;\nStep 4 Strain the broth and pour back into the pot; discard the bones and aromatics.\nStep 5 Heat the broth until simmering. Drop in the meatballs;\nStep 6 Using a kitchen spider, blanch the sliced carrot and spinach separately in the hot broth;\nStep 7 Divide the noodles among three bowls.\nStep 8 Divide the carrot slices and spinach into three portions and put in the bowls next to the noodles;\nStep 9 Ladle the hot soup and meatballs directly into the bowls;\nStep 10 Top each bowl with crisp-fried shallots and split hard-boiled eggs, if using.',
  first: 'Step 1 Place the beef bones in a pot. Cover with water.',
  second: 'Step 2 Bring to the boil, skim off any scum that rises.',
  third: 'Step 3 Add the ginger, garlic, cinnamon, cardamom, cloves, and peppercorns. Simmer for at least two hours.',
  fourth: 'Step 4 Strain the broth and pour back into the pot; discard the bones and aromatics.',
  fifth: 'Step 5 Heat the broth until simmering. Drop in the meatballs.',
  sixth: 'Step 6 Using a ​kitchen spider, blanch the sliced carrot and spinach separately in the hot broth.',
  seventh: 'Step 7 Divide the noodles among three bowls.',
  eighth: 'Step 8 Divide the carrot slices and spinach into three portions and put in the bowls next to the noodles.',
  ninth: 'Step 9 Ladle the hot soup and meatballs directly into the bowls.',
  tenth: 'Step 10 Top each bowl with crisp-fried shallots and split hard-boiled eggs, if using.',
},
{
  id: 'gado_gado',
  name: 'Gado Gado',
  description: 'Gado-gado (Indonesian or Betawi) is an Indonesian salad of raw, slightly boiled, blanched or steamed vegetables and hard-boiled eggs, boiled potato, fried tofu and tempeh, and lontong (rice wrapped in a banana leaf), served with a peanut sauce dressing.',
  ingredients: '1 tbsp vegetable oil,\n200g firm tofu chopped into small chunks,\n250g cooked potatoes (leftover roast potatoes work well) chopped into chunks,\n3 eggs,\n100g green beans halved lengthways,\n250g Chinese cabbage finely shredded,\n½ cucumber (or 1 baby cucumber) thinly sliced,\n100g beansprouts,\n1 carrot shredded,\nhandful coriander leaves picked and roughly chopped,\nhandful prawn crackers,\n4 tbsp crispy onions,\n50g peanut butter,\n3 tbsp kecap manis (or 2 ½ tbsp soy sauce and ½ tbsp honey),\n2 tsp shrimp paste or dried crayfish,\n1 tbsp fish sauce,\n1 tbsp soft dark brown sugar,\n1 garlic clove crushed,\n2 fat red chillies finely chopped,\n150ml coconut milk,\njuice 1 lime',
  howtocook: 'Step 1 Heat the oil in a large frying pan or wok and boil a small saucepan of water. Fry the tofu for a few mins each side until brown and crispy, then transfer to a plate. Add the potatoes to the frying pan and cook for a few mins until they are warmed through and starting to crisp, then tip onto the same plate and set aside to cool;\nStep 2 Add the eggs to the boiling water and cook for 7 mins, then plunge them straight into cold water. Fill the saucepan with fresh water, bring to the boil and add the beans. Cook for 2-3 mins until just tender. Drain and run under cold water until cool;\nStep 3 To make the peanut dressing, put the peanut butter and kecap manis in a bowl and mash together with a fork until smooth and combined. Whisk in the remaining ingredients;\nStep 4 Put the tofu, potatoes, beans, cabbage, cucumber, beansprouts, carrot and coriander in a large bowl or arrange on a platter. Drizzle over half the dressing, reserving the rest for people to help themselves. Break the prawn crackers in your hands and scatter over. Peel and quarter the eggs, and serve on top with the crispy onions. Toss together just before serving.',
  first: 'Step 1 Heat the oil in a large frying pan or wok and boil a small saucepan of water. Fry the tofu for a few mins each side until brown and crispy, then transfer to a plate. Add the potatoes to the frying pan and cook for a few mins until they are warmed through and starting to crisp, then tip onto the same plate and set aside to cool.',
  second: 'Step 2 Add the eggs to the boiling water and cook for 7 mins, then plunge them straight into cold water. Fill the saucepan with fresh water, bring to the boil and add the beans. Cook for 2-3 mins until just tender. Drain and run under cold water until cool.',
  third: 'Step 3 To make the peanut dressing, put the peanut butter and kecap manis in a bowl and mash together with a fork until smooth and combined. Whisk in the remaining ingredients.',
  fourth: 'Step 4 Put the tofu, potatoes, beans, cabbage, cucumber, beansprouts, carrot and coriander in a large bowl or arrange on a platter. Drizzle over half the dressing, reserving the rest for people to help themselves. Break the prawn crackers in your hands and scatter over. Peel and quarter the eggs, and serve on top with the crispy onions. Toss together just before serving.',
  fifth: '',
  sixth: '',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'lumpia_semarang',
  name: 'Lumpia Semarang',
  description: 'Lumpia Semarang is like a spring roll containing bamboo shoots, eggs, and chicken or shrimp. The taste of semarang spring rolls is a blend of flavors between Chinese and Indonesian cuisine because it was first made by a Chinese descendant who married an Indonesian and settled in Semarang, Central Java. Stuffed with tender bamboo shoots, juicy shrimps, chicken, vegetables and a variety of condiments, this roll is definitely hearty enough for a light lunch or a filling snack.',
  ingredients: '15 sheets spring roll warpper (size 215 mm x 215 mm),\n500 g shredded fresh bamboo shoot,\n500 g peeled shrimp chopped,\n2 tbsp ground dried shrimp,\n5 cloves garlic minced,\n1 tsp ground white pepper,\n2 tbsp abalone sauce,\n1 tbsp oyster sauce,\n1 tbsp mushroom soy sauce (original recipe called for soy sauce),\n1 tbsp Indonesian sweet soy sauce (kecap manis),\n150 ml homemade shrimp broth (can be substituted for water and dried shrimp),\n3 tbsp oil for stir frying,\nBrown sauce,\n250 ml water,\n6 cloves garlic minced,\n85 g coconut sugar shredded (Indonesian: gula merah,original recipe called for 100 g coconut sugar),\n½ tsp salt,\n1 tbsp corn starch or tapioca flour dissolve in a small amount of water,\nbird eyes chilies chopped',
  howtocook: 'Step 1 Create the Brown Sauce, In a saucepan, bring water, coconut sugar, salt and garlic to a boil. Thicken with tapioca flour mixture, stir until mixed. Remove from heat and set aside;\nStep 2 Cook bamboo shoot with water and 1 tbsp sugar until boiled, drain. Stir fry garlic until fragrant, add shrimp, bamboo shoot, ground dried shrimp, oyster sauce, kecap manis, white pepper and salt. Add broth, cook until water evaporates;\nStep 3 Place 2- 3 tbsp filling on the wrapper. Fold over the corner that faces away from us. Brush brown sauce onto this corner for gluing. Fold over the left-facing and right-facing corners. Roll the lumpia toward us, onto the remaining corner of the wrapper. Examine the wrapper to ensure that it is fully sealed. Do until all filling and wrappers done;\nStep 4 Deep fry until golden brown.',
  first: 'Step 1 Create the Brown Sauce, In a saucepan, bring water, coconut sugar, salt and garlic to a boil. Thicken with tapioca flour mixture, stir until mixed. Remove from heat and set aside.',
  second: 'Step 2 Cook bambo shoot with water and 1 tbsp sugar until boiled, drain. Stir fry garlic until fragrant, add shrimp, bamboo shoot, ground dried shrimp, oyster sauce, kecap manis, white pepper and salt. Add broth, cook until water evaporates.',
  third: 'Step 3 Place 2 - 3 tbsp filling on the wrapper. Fold over the corner that faces away from us. Brush brown sauce onto this corner for gluing. Fold over the left-facing and right-facing corners. Roll the lumpia toward us, onto the remaining corner of the wrapper. Examine the wrapper to ensure that it is fully sealed. Do until all filling and wrappers done.',
  fourth: 'Step 4 Deep fry until golden brown.',
  fifth: '',
  sixth: '',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'rendang',
  name: 'Rendang',
  description: 'Beef Rendang is one of the original cuisines of Minangkabau descent and Sumatra’s culture. It is served at special occasions to honor guests and during festive seasons. It is a delicious Indonesian dish prepared with a myriad of herbs and spices cooking for a few hours until all the liquids have been completely absorbed by the meat. Beef rendang is best eaten with steamed rice and condiments such as fried onions and chili pieces. Here is the good news.  You do not need to travel to Sumatra of Indonesia. You can just recreate the world’s best food at home by following this beef rendang recipe.',
  ingredients: '1½ lbs. (0.6 kg) boneless beef short ribs cut into cubes,\n5 tablespoons cooking oil,\n1 stick cinnamon about 2 inch length,\n3 cloves,\n3 star anise,\n3 cardamom pods,\n1 lemongrass cut into 4 inch length and pounded,\n1 cup thick coconut milk coconut cream,\n1 cup water,\n2 teaspoons tamarind pulp soaked in some warm water for the juice and discard the seeds,\n6 kaffir lime leaves very finely sliced,\n6 tablespoons kerisik toasted coconut,\n1 tablespoon sugar or palm sugar to taste,\nsalt to taste,\n5 shallots,\n1 inch galangal,\n3 lemongrass (white part only),\n5 cloves garlic,\n1 inch ginger,\n10-12 dried chilies soaked in warm water and seeded.',
  howtocook: 'Step 1 Chop the spice paste ingredients and then blend it in a food processor until fine;\nStep 2 Heat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat;\nStep 3 Lower the heat to low, cover the lid, and simmer for 1 to 1½ hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.',
  first: 'Step 1 Chop the spice paste ingredients and then blend it in a food processor until fine.',
  second: 'Step 2 Heat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat.',
  third: 'Step 3 Lower the heat to low, cover the lid, and simmer for 1 to 1½ hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.',
  fourth: '',
  fifth: '',
  sixth: '',
  seventh: '',
  eighth: '',
  ninth: '',
  tenth: '',
},
{
  id: 'telur_asin',
  name: 'Telur Asin',
  description: 'A salted duck egg (Telur Asin) is an Asian preserved food product made by soaking duck eggs in brine, or packing each egg in damp, salted charcoal. In Asian supermarkets, these eggs are sometimes sold covered in a thick layer of salted charcoal paste. The eggs may also be sold with the salted paste removed, wrapped in plastic, and vacuum packed. From the salt curing process, the salted duck eggs have a briny aroma, a gelatin-like egg white and a firm-textured, round yolk that is bright orange-red in color.',
  ingredients: '10 duck egg,\n1000 ml water,\n100 gr salt,\n1 kg rub ash,\na bucket',
  howtocook: 'Step 1 Prepare a plastic bucket, sandpaper, pan, stirrer, and egg storage container;\nStep 2 Prepare water in a plastic bucket to wash the eggs;\nStep 3 Wash raw duck eggs. To make it easier to remove dirt on the egg shell. You can use the help of a toothbrush;\nStep 4 dry the eggs;\nStep 5 Rub the egg with sandpaper to open the pores in the eggshell. The goal is to allow the salt mixture to soak into the eggs;\nStep 6 Make a mixture for salting eggs by mixing red rub ash in a ratio of 1:1;\nStep 7 Mix with water until it becomes a paste;\nStep 8 Coat the duck egg with dough about 1-2 mm thick;\nStep 9 Store eggs in a container for 15-20 days. The longer the eggs are stored, the more salty and delicious they will taste;\nStep 10 After enough time is stored, clean the eggs and then cook by steaming or boiling;',
  first: 'Step 1 Prepare a plastic bucket, sandpaper, pan, stirrer, and egg storage container.',
  second: 'Step 2 Prepare water in a plastic bucket to wash the eggs.',
  third: 'Step 3 Wash raw duck eggs. To make it easier to remove dirt on the egg shell. You can use the help of a toothbrush.',
  fourth: 'Step 4 dry the eggs.',
  fifth: 'Step 5 Rub the egg with sandpaper to open the pores in the eggshell. The goal is to allow the salt mixture to soak into the eggs.',
  sixth: 'Step 6 Make a mixture for salting eggs by mixing red rub ash in a ratio of 1:1.',
  seventh: 'Step 7 Mix with water until it becomes a paste.',
  eighth: 'Step 8 Coat the duck egg with dough about 1-2 mm thick.',
  ninth: 'Step 9 Store eggs in a container for 15-20 days. The longer the eggs are stored, the more salty and delicious they will taste.',
  tenth: 'Step 10 After enough time is stored, clean the eggs and then cook by steaming or boiling.',
}];

module.exports = foods;